defaults:
  - lewm
  - _self_

output_model_name: lewm_moda64_exact_drop0
subdir: pusht_moda64_exact_drop0_5090_gpu0

wandb:
  enabled: false

use_moda: true
depth_start_layer: 1

predictor:
  depth: 64
  dropout: 0.0
